name: Sync promtail-app from upstream

on:
  # schedule:
  #   - cron: '*/5 7-20 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-promtail-app-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync promtail-app from upstream
        uses: giantswarm/subtree-util@additional-adjustments
        with:
          source_tag_wildcard: "promtail-*"
          source_path: charts/promtail
          target_github_token: ${{ secrets.ARCHITECT_GITHUB_TOKEN }}
          target_repository: ubergesundheit/promtail-app
          target_path: helm/promtail
